# Generated by Django 5.1.4 on 2024-12-23 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userpreference_theme_alter_userpreference_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoroMinutes', models.PositiveIntegerField(default=25)),
                ('pomodoroSeconds', models.PositiveIntegerField(default=0)),
                ('breakMinutes', models.PositiveIntegerField(default=5)),
                ('breakSeconds', models.PositiveIntegerField(default=0)),
                ('longBreakMinutes', models.PositiveIntegerField(default=15)),
                ('longBreakSeconds', models.PositiveIntegerField(default=0)),
                ('longBreakInterval', models.PositiveIntegerField(default=4)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('default', 'Default')], default='default', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
