# Generated by Django 5.1.4 on 2024-12-23 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pomodoropreference_delete_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='longBreakInterval',
            new_name='long_break_interval',
        ),
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='longBreakMinutes',
            new_name='long_break_minutes',
        ),
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='breakSeconds',
            new_name='long_break_seconds',
        ),
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='pomodoroMinutes',
            new_name='pomodoro_minutes',
        ),
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='longBreakSeconds',
            new_name='pomodoro_seconds',
        ),
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='breakMinutes',
            new_name='short_break_minutes',
        ),
        migrations.RenameField(
            model_name='pomodoropreference',
            old_name='pomodoroSeconds',
            new_name='short_break_seconds',
        ),
        migrations.AlterField(
            model_name='pomodoropreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
